services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb

volumes:
  mongodb-data:
