services:
  mongodb:
    image: mongo:5.0
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
  quote-bot:
    env_file: config.env
    build: .
    volumes:
    - attachments:/usr/src/app/attachments/

volumes:
  mongodb-data:
  attachments:
